print('Division euclidienne de deux entiers')
a=int(input('Saisissez le dividende :'))
b=int(input('Saisissez le diviseur :'))
print('Le quotient de',a,'par',b,'vaut', a//b)
print('Le reste de',a,'par',b,'vaut', a%b)